#enable-self-preservation: false

eureka:  
  server:
    enable-self-preservation: false   
  instance:
    hostname: localhost   
  client:
    fetch-registry: false
    register-with-eureka: false
    healthcheck:
      enabled: true 
server: 
  port: 8070 