spring:
  application:
     name: stock-service


eureka:
  instance:
    instance-id: ${spring.application.name}:${random.value} 
  client:
    serviceUrl:
      defaultZone: http://localhost:8070/eureka
      
server:
  port: 8073 

